### ISSUE TITLE
Removing the GPLv3, adding AFFERO?

### ISSUE THREAD

**Issue by ghost** [drrr-like-chat/drrr-like-chat#1]

**Comment by suin** [comment]
@Platox This product is now developed under AGPLv3. So fork of this product must be licensed under AGPLv3. 

Drrr-like-chat is used to be free software. However, someone modified our code but they didn't commit to the project. They used fork versions only for themselves. This is anti-free software. So I choose the license which is much more free.

However, if you have the old version which licensed under GPLv3, you can be modified and distributed it under GPLv3 not AGPL. No effects GPLv3 version. Don't worry.

**Comment by suin** [comment]
If you have any questions, feel free to reopen this issue :)
